// Generated from design/academy/digital-marketing-course.html by design/academy/generate.mjs.
// The markup ships verbatim so the live page stays identical to the approved
// design; regenerate this file rather than editing it by hand.
import type { AcademyPage } from './types';

export const COURSE: AcademyPage = {
  url: "/academy/digital-marketing-course/",
  title: "Digital Marketing Course with AI in Kochi | WizGrowth",
  description: "Beginner to job-ready digital marketing course in Kochi: SEO, content, AI search and Google Ads. 12 weeks, ₹30,000, max 15 students.",
  schema: {"@context":"https://schema.org","@graph":[{"@type":"Course","name":"Digital Marketing Course with AI in Kochi","description":"A 12-week live digital marketing course covering SEO, content, AI search, Google Ads and measurement.","courseMode":"online","timeRequired":"P12W","provider":{"@type":"Organization","name":"WizGrowth Academy","url":"https://www.wizgrowth.com/academy/"},"offers":{"@type":"Offer","price":"30000","priceCurrency":"INR","availability":"https://schema.org/InStock"}},{"@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Do I need a marketing or technical background?","acceptedAnswer":{"@type":"Answer","text":"No. Week 1 starts from zero. You need to be comfortable using a laptop and willing to write."}},{"@type":"Question","name":"Is there placement?","acceptedAnswer":{"@type":"Answer","text":"No placement is promised. You leave with a portfolio employers can verify, interview preparation and introductions to businesses and agencies in the WizGrowth network."}},{"@type":"Question","name":"Why only 15 students?","acceptedAnswer":{"@type":"Answer","text":"Because the product is personal review of your work every week. The batch stays small so that standard does not slip."}},{"@type":"Question","name":"Is this online or in person?","acceptedAnswer":{"@type":"Answer","text":"Live online, with a Kerala-based batch. Occasional in-person meetups in Kochi can happen when the batch wants them."}},{"@type":"Question","name":"Will this get me a performance-marketing job?","acceptedAnswer":{"@type":"Answer","text":"Not by itself. Google Ads is covered properly and Meta only at a basic level. If you want a Meta-focused career, this is not the most direct course."}},{"@type":"Question","name":"Is there a certificate?","acceptedAnswer":{"@type":"Answer","text":"Yes, there is a completion letter. Your website, Search Console data and portfolio should matter more to an employer."}}]}]},
  wizMessages: ["Ready to build something real?","Twelve weeks. One real site.","Your work becomes the portfolio."],
  html: `<div class="top"><div class="shell"><header class="site-header">
<a aria-label="WizGrowth Academy home" class="brand-lockup" href="/academy/"><span class="brand-word">wizgrowth</span><span aria-hidden="true" class="brand-divider"></span><span class="brand-section">academy</span></a>
<nav aria-label="Academy navigation" class="desktop-nav"><a href="/academy/">Academy</a><a href="#curriculum">Curriculum</a><a href="#fees">Fees</a><a href="#faq">FAQ</a></nav>
<a class="header-cta" href="https://wa.me/917907551261?text=Hi%20WizGrowth%20Academy%20%E2%80%94%20I'd%20like%20to%20join%20the%20next%2012-week%20Digital%20Marketing%20Course%20with%20AI." target="_blank" rel="noopener noreferrer" data-lead-open data-lead-course="Digital Marketing Course with AI"><span>Reserve a seat</span><span class="header-cta-icon"><svg aria-hidden="true" class="arrow"><use href="#arrow-up"></use></svg></span></a>
<button aria-expanded="false" aria-label="Open menu" class="menu-toggle" data-menu=""><svg viewbox="0 0 24 24"><path d="M3 8h18M3 16h18" fill="none" stroke-width="1.5"></path></svg></button>
</header></div></div>
<nav aria-label="Mobile academy navigation" class="mobile-nav-v4 shell" data-mobile-nav=""><a href="/academy/">Academy</a><a href="#curriculum">Curriculum</a><a href="#fees">Fees</a><a href="#faq">FAQ</a></nav>
<main>
<section class="hero"><div class="shell"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow kicker">WIZGROWTH ACADEMY / COURSE 01</div><h1>Digital Marketing Course with AI <span class="accent">in Kochi.</span><span class="h1-tail">SEO, content and AI search — beginner to job-ready in 12 weeks.</span></h1><p>Build a real website, rank it in Google, publish content built for AI search, run your first Google Ads campaign, and leave with a portfolio employers can check.</p><div class="hero-actions"><a class="button lime" href="https://wa.me/917907551261?text=Hi%20WizGrowth%20Academy%20%E2%80%94%20I'd%20like%20to%20join%20the%20next%2012-week%20Digital%20Marketing%20Course%20with%20AI." target="_blank" rel="noopener noreferrer" data-lead-open data-lead-course="Digital Marketing Course with AI">Reserve a seat <svg class="arrow"><use href="#arrow-up"></use></svg></a><a class="button ghost" href="#curriculum">See the curriculum <svg class="arrow"><use href="#arrow-up"></use></svg></a></div><div class="in-short"><span>IN SHORT</span><p><strong>WizGrowth Academy</strong> runs this digital marketing course in Kochi for final-year students, freshers and career-switchers. It runs for 12 weeks, costs ₹30,000 and is capped at 15 students.</p></div></div><div aria-hidden="true" class="hero-art"><div class="wiz-hero" data-wiz-hero="">
<span class="wiz-stage-label">LITTLE WIZ / STUDY MODE</span>
<div class="wiz-speech" data-wiz-speech="">Ready to build something real?</div>
<span class="wiz-chip a">BUILD</span><span class="wiz-chip b">RANK</span><span class="wiz-chip c">SHOW</span>
<svg aria-hidden="true" class="wiz-scene-v4" viewbox="0 0 500 282">
<defs>
<lineargradient id="academy-wiz-body-fill" x1="0" x2=".85" y1="0" y2="1"><stop offset="0" stop-color="#d9ff97"></stop><stop offset=".58" stop-color="#c5f86b"></stop><stop offset="1" stop-color="#a3d84e"></stop></lineargradient>
<lineargradient id="academy-wiz-ground" x1="0" x2="1" y1="0" y2="0"><stop offset="0" stop-color="#c3b9fb" stop-opacity="0"></stop><stop offset=".5" stop-color="#c3b9fb" stop-opacity=".3"></stop><stop offset="1" stop-color="#c3b9fb" stop-opacity="0"></stop></lineargradient>
</defs>
<g fill="none" stroke="#414737" stroke-width="1"><path d="M63 75v10m-5-5h10M460 89v10m-5-5h10M116 244v10m-5-5h10"></path><ellipse cx="263" cy="247" rx="180" ry="23" stroke="url(#academy-wiz-ground)"></ellipse><ellipse cx="263" cy="247" rx="135" ry="16" stroke="url(#academy-wiz-ground)"></ellipse></g>
<ellipse class="wiz-shadow-v4" cx="249" cy="240" fill="#060805" opacity=".8" rx="66" ry="10"></ellipse>
<g class="wiz-buddy-v4">
<g class="wiz-sprout-v4"><path d="M246 78C242 49 248 39 263 25" fill="none" stroke="#c3b9fb" stroke-linecap="round" stroke-width="6"></path><path d="M249 59C216 62 211 34 209 25C235 20 252 33 249 59Z" fill="#c3b9fb" stroke="#141511" stroke-width="3"></path><path d="M250 49C247 24 266 13 288 15C286 38 273 52 250 49Z" fill="#c5f86b" stroke="#141511" stroke-width="3"></path></g>
<g stroke="#171b12" stroke-width="4"><path d="M206 209v19c-23-3-31 10-25 16c7 9 42 5 46-4l4-27" fill="#c3b9fb"></path><path d="M266 209v29c5 9 40 12 46 3c5-8-5-15-24-13v-20" fill="#c3b9fb"></path></g>
<path d="M179 149C156 153 151 171 156 185" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="12"></path>
<g class="wiz-arm-right-v4"><path d="M301 146C325 150 340 137 342 119" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="12"></path><path d="m338 120-6-7m11 5 6-9" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="6"></path></g>
<path d="M240 67C285 59 308 80 315 123C321 159 313 193 298 208C280 227 216 229 193 209C175 195 171 163 175 131C178 98 194 73 222 70Z" fill="url(#academy-wiz-body-fill)" stroke="#17220b" stroke-width="3"></path>
<path d="M190 127c0-17 6-32 19-39" fill="none" opacity=".8" stroke="#e7ffb8" stroke-linecap="round" stroke-width="5"></path>
<g class="wiz-gaze-v4"><ellipse cx="222" cy="135" fill="#202719" rx="10" ry="15"></ellipse><ellipse cx="271" cy="135" fill="#202719" rx="10" ry="15"></ellipse><ellipse cx="225" cy="130" fill="#fff" rx="3" ry="4"></ellipse><ellipse cx="274" cy="130" fill="#fff" rx="3" ry="4"></ellipse></g>
<ellipse cx="203" cy="157" fill="#c3b9fb" opacity=".75" rx="11" ry="5"></ellipse><ellipse cx="288" cy="157" fill="#c3b9fb" opacity=".75" rx="11" ry="5"></ellipse>
<path d="M231 163q15 16 29-1" fill="none" stroke="#253219" stroke-linecap="round" stroke-width="4"></path><path d="m238 202 5 7 9-15" fill="none" stroke="#5b7936" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"></path>
</g>
<g class="wiz-sparkles-v4" stroke="#c3b9fb" stroke-linecap="round" stroke-width="2"><path d="M156 83v12m-6-6h12"></path><path d="m331 48 3 5m12 4 5-1"></path><path d="m352 213 2 8m-6-5 10-2"></path></g>
</svg>
<div class="wiz-footnote"><strong>LEARN → BUILD → SHOW</strong>REAL WORK. REAL FEEDBACK.</div>
</div></div></div></div></section>
<div class="facts"><div class="fact"><span>Duration</span><b>12 weeks</b></div><div class="fact"><span>Sessions</span><b>24 live sessions</b></div><div class="fact"><span>Schedule</span><b>Thu–Fri / weekends</b></div><div class="fact"><span>Fee</span><b>₹30,000</b></div><div class="fact"><span>Batch size</span><b>Max 15</b></div><div class="fact"><span>Format</span><b>Live online</b></div></div>
<section class="section"><div class="shell"><div class="section-head"><span class="eyebrow">FIT CHECK</span><span class="num">01 / 06</span></div><div class="split"><h2 class="display">Is this course <span class="muted">for you?</span></h2><p class="lede">It starts from zero, but it is not passive. You need a laptop, stable internet and 6–8 hours a week including class and project work.</p></div><div class="fit-grid"><div class="fit-pane"><h3>Yes, if...</h3><ul><li>You are a final-year student or graduate from any stream.</li><li>You are a fresher or have 0–2 years of experience in any field.</li><li>You are switching into marketing and want practical proof of your work.</li><li>You can spend 6–8 hours a week and are willing to write.</li><li>You can budget about ₹2,000–3,000 for domain, hosting and a small ad test.</li></ul></div><div class="fit-pane alt"><h3>Not for you, honestly, if...</h3><ul><li>You specifically want a Meta ads or performance-marketing job.</li><li>You want a recorded course you can watch entirely at your own pace.</li><li>You are not ready to publish real work and have it reviewed live.</li></ul></div></div></div></section>
<section class="section soft"><div class="shell"><div class="section-head"><span class="eyebrow">BY WEEK 12</span><span class="num">02 / 06</span></div><h2 class="display">What you will be able <span class="muted">to do.</span></h2><div class="number-grid"><div class="number-item"><span class="n">01</span><p>Research keywords and map them to a real website.</p></div><div class="number-item"><span class="n">02</span><p>Build and optimise a site that Google can crawl, index and rank.</p></div><div class="number-item"><span class="n">03</span><p>Run a technical SEO audit and fix the issues it finds.</p></div><div class="number-item"><span class="n">04</span><p>Plan and publish content with AI tools while keeping it accurate and human.</p></div><div class="number-item"><span class="n">05</span><p>Make a brand easier to find in ChatGPT, Perplexity and AI Overviews.</p></div><div class="number-item"><span class="n">06</span><p>Set up and optimise a Google Search campaign with tracking.</p></div><div class="number-item"><span class="n">07</span><p>Read Search Console and GA4 and build a manager-ready report.</p></div><div class="number-item"><span class="n">08</span><p>Present your portfolio in an interview with proof instead of claims.</p></div></div></div></section>
<section class="section" id="curriculum"><div class="shell"><div class="section-head"><span class="eyebrow">CURRICULUM</span><span class="num">03 / 06</span></div><div class="split"><h2 class="display">12 weeks.<br/><span class="muted">Three chapters.</span></h2><p class="lede">The full syllabus stays available without putting twelve competing cards on the page. Open a chapter to see each week and the work you ship.</p></div><div class="curriculum">
<details open=""><summary><span class="phase">01 / FOUNDATION</span><h3>Weeks 01–04</h3><span class="weeks">Positioning · Website · Search · On-page SEO</span><span class="plus">+</span></summary><div class="curriculum-body"><div class="week"><span class="wk">W01</span><div><b>Marketing in 2026</b><p>Customer journey, funnel, ICP, positioning, Google, social and AI discovery. Build: practice business, positioning and ICP.</p></div></div><div class="week"><span class="wk">W02</span><div><b>Websites that work</b><p>Site structure, core pages, copy basics and trust signals. Build: website live with three core pages and analytics installed.</p></div></div><div class="week"><span class="wk">W03</span><div><b>How search works</b><p>Crawling, indexing, ranking, intent and keyword research. Build: a 100-keyword map clustered by intent.</p></div></div><div class="week"><span class="wk">W04</span><div><b>On-page and local SEO</b><p>Titles, metas, headings, internal links, schema, images and Google Business Profile. Build: every page optimised and indexed.</p></div></div></div></details>
<details><summary><span class="phase">02 / BUILD</span><h3>Weeks 05–08</h3><span class="weeks">Technical SEO · Content · AI-assisted production · AI search</span><span class="plus">+</span></summary><div class="curriculum-body"><div class="week"><span class="wk">W05</span><div><b>Technical SEO</b><p>Speed, mobile, Core Web Vitals, crawl errors, sitemaps and redirects. Build: technical audit with fixes done.</p></div></div><div class="week"><span class="wk">W06</span><div><b>Content strategy</b><p>Topic clusters, pillar pages, content calendar and funnel stages. Build: 3-month calendar and pillar article.</p></div></div><div class="week"><span class="wk">W07</span><div><b>AI-assisted content production</b><p>Research, briefs, drafting, editing, fact-checking, brand voice and repurposing. Build: four articles and five social posts.</p></div></div><div class="week"><span class="wk">W08</span><div><b>Getting found in AI search</b><p>How LLMs and AI Overviews choose sources, entities, structured content and off-page visibility. Build: AI-visibility audit and five placements.</p></div></div></div></details>
<details><summary><span class="phase">03 / GROW</span><h3>Weeks 09–12</h3><span class="weeks">Google Ads · Paid + organic · Measurement · Career</span><span class="plus">+</span></summary><div class="curriculum-body"><div class="week"><span class="wk">W09</span><div><b>Google Search Ads</b><p>Campaign structure, match types, negatives, Quality Score, ad copy and conversion tracking. Build: a live Search campaign.</p></div></div><div class="week"><span class="wk">W10</span><div><b>Optimisation and Meta fundamentals</b><p>Optimising Google Ads, how paid and organic work together, plus Meta basics. Build: optimisation write-up and small Meta test.</p></div></div><div class="week"><span class="wk">W11</span><div><b>Measurement</b><p>Search Console, GA4, UTMs and Looker Studio. Build: your dashboard and present a five-minute report.</p></div></div><div class="week"><span class="wk">W12</span><div><b>Getting hired</b><p>Roles, interviews, LinkedIn, portfolio and freelancing. Build: final portfolio and updated LinkedIn profile.</p></div></div></div></details>
</div></div></section>
<section class="section lilac"><div class="shell"><div class="section-head"><span class="eyebrow">TOOLS</span><span class="num">04 / 06</span></div><h2 class="display">The tools are secondary.<br/><span style="color:#554c73">The thinking comes first.</span></h2><div class="tools-line" style="margin-top:46px"><span>SEARCH CONSOLE <i>✦</i> GA4 <i>✦</i> TAG MANAGER <i>✦</i> CHATGPT / CLAUDE <i>✦</i> PERPLEXITY <i>✦</i> GOOGLE ADS <i>✦</i> WORDPRESS / FRAMER <i>✦</i> LOOKER STUDIO</span></div></div></section>
<section class="section" id="fees"><div class="shell"><div class="section-head"><span class="eyebrow">FEES</span><span class="num">05 / 06</span></div><div class="price-grid"><div><h2 class="display">Fees, <span class="muted">plainly.</span></h2><div class="price">₹30,000<small>/ 12 weeks</small></div></div><div class="price-note"><p><b>Course fee: ₹30,000.</b> Pay in full or in three instalments. The only extra cost is your own domain, hosting and a small ad budget of about ₹2,000–3,000.</p><p>Refund in full if you withdraw before the third session.</p></div></div></div></section>
<section class="section soft" id="faq"><div class="shell"><div class="section-head"><span class="eyebrow">FAQ</span><span class="num">06 / 06</span></div><h2 class="display">Frequently asked questions.</h2><div class="faq"><details><summary><span>Do I need a marketing or technical background?</span><span>+</span></summary><p>No. Week 1 starts from zero. You need to be comfortable using a laptop and willing to write.</p></details><details><summary><span>Is there placement?</span><span>+</span></summary><p>No placement is promised. You leave with a portfolio employers can verify, interview preparation and introductions to businesses and agencies in the WizGrowth network.</p></details><details><summary><span>Why only 15 students?</span><span>+</span></summary><p>Because the product is personal review of your work every week. The batch stays small so that standard does not slip.</p></details><details><summary><span>Is this online or in person?</span><span>+</span></summary><p>Live online, with a Kerala-based batch. Occasional in-person meetups in Kochi can happen when the batch wants them.</p></details><details><summary><span>Will this get me a performance-marketing job?</span><span>+</span></summary><p>Not by itself. Google Ads is covered properly and Meta only at a basic level. If you want a Meta-focused career, this is not the most direct course.</p></details><details><summary><span>Is there a certificate?</span><span>+</span></summary><p>Yes, there is a completion letter. Your website, Search Console data and portfolio should matter more to an employer.</p></details></div></div></section>
<section class="cta" id="enquire"><div class="cta-code">12</div><div class="shell"><div class="cta-grid"><div><div class="eyebrow">NEXT BATCH</div><h2>Ready to build something real?</h2></div><div class="cta-copy"><p>15 seats per batch. Message WizGrowth with your background and we will tell you whether the course fits — including if it does not.</p><a class="button dark" href="https://wa.me/917907551261?text=Hi%20WizGrowth%20Academy%20%E2%80%94%20I'd%20like%20to%20join%20the%20next%2012-week%20Digital%20Marketing%20Course%20with%20AI." target="_blank" rel="noopener noreferrer" data-lead-open data-lead-course="Digital Marketing Course with AI">Reserve a seat on WhatsApp <svg class="arrow"><use href="#arrow-up"></use></svg></a></div></div></div></section>
</main>
<footer class="site-footer"><div class="shell"><div class="footer-top"><p>Independent thinking.<br/>Forward momentum.</p><div class="footer-links"><a href="/academy/">Academy</a><a href="/academy/advanced-digital-marketing-mentorship/">Working professionals</a><a href="/academy/digital-marketing-for-business-owners/">Business owners</a></div></div><div class="footer-signature"><div class="signature-main"><a class="signature-word" href="/">wiz<span>growth</span></a><button class="back-top" data-top=""><svg class="arrow"><use href="#arrow-up"></use></svg></button></div></div><div class="footer-bottom"><span>Copyright © WizGrowth Inc. 2026</span><span>A LITTLE WIZ. A LOT OF POSSIBILITY.</span><span>KERALA, INDIA ↗</span></div></div></footer>`,
};
