// Generated from design/academy/advanced-mentorship.html by design/academy/generate.mjs.
// The markup ships verbatim so the live page stays identical to the approved
// design; regenerate this file rather than editing it by hand.
import type { AcademyPage } from './types';

export const MENTORSHIP: AcademyPage = {
  url: "/academy/advanced-digital-marketing-mentorship/",
  title: "Advanced Digital Marketing for Professionals | WizGrowth",
  description: "Advanced digital marketing course for working professionals with 1–5 years of experience. 12 weeks plus optional monthly mentorship.",
  schema: {"@context":"https://schema.org","@graph":[{"@type":"Course","name":"Advanced Digital Marketing Mentorship for Working Professionals","description":"A 12-week advanced digital marketing course for working professionals, with optional monthly mentorship afterwards.","courseMode":"online","timeRequired":"P12W","provider":{"@type":"Organization","name":"WizGrowth Academy","url":"https://www.wizgrowth.com/academy/"},"offers":{"@type":"Offer","price":"30000","priceCurrency":"INR","availability":"https://schema.org/InStock"}},{"@type":"FAQPage","mainEntity":[{"@type":"Question","name":"Why join the same course as freshers?","acceptedAnswer":{"@type":"Answer","text":"The fundamentals are shared, but the second session each week reviews your own work at your level. Your private calls and tougher output requirements keep the professional track distinct."}},{"@type":"Question","name":"Can I join the mentorship without the course?","acceptedAnswer":{"@type":"Answer","text":"Not in the first year. The mentorship assumes the shared method and vocabulary from the 12-week course."}},{"@type":"Question","name":"Will my employer pay?","acceptedAnswer":{"@type":"Answer","text":"They may. WizGrowth can provide an invoice and a syllabus letter on request."}}]}]},
  wizMessages: ["You already know the tools.","Now own the growth number.","Strategy looks good on you."],
  html: `<div class="top"><div class="shell"><header class="site-header">
<a aria-label="WizGrowth Academy home" class="brand-lockup" href="/academy/"><span class="brand-word">wizgrowth</span><span aria-hidden="true" class="brand-divider"></span><span class="brand-section">academy</span></a>
<nav aria-label="Academy navigation" class="desktop-nav"><a href="/academy/">Academy</a><a href="#themes">Themes</a><a href="#fees">Fees</a><a href="#faq">FAQ</a></nav>
<a class="header-cta" href="#enquire"><span>Apply</span><span class="header-cta-icon"><svg aria-hidden="true" class="arrow"><use href="#arrow-up"></use></svg></span></a>
<button aria-expanded="false" aria-label="Open menu" class="menu-toggle" data-menu=""><svg viewbox="0 0 24 24"><path d="M3 8h18M3 16h18" fill="none" stroke-width="1.5"></path></svg></button>
</header></div></div>
<nav aria-label="Mobile academy navigation" class="mobile-nav-v4 shell" data-mobile-nav=""><a href="/academy/">Academy</a><a href="#themes">Themes</a><a href="#fees">Fees</a><a href="#faq">FAQ</a></nav>
<main><section class="hero"><div class="shell"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow kicker">WIZGROWTH ACADEMY / WORKING PROFESSIONALS</div><h1>Advanced Digital Marketing Mentorship <span class="accent">for Working Professionals.</span><span class="h1-tail">Move from running one channel to owning organic growth.</span></h1><p>For marketers with 1–5 years' experience who already execute SEO, content or social and want the next role. Work on a live business website, then continue in a small monthly mentorship group.</p><div class="hero-actions"><a class="button lime" href="https://wa.me/917907551261?text=Hi%20WizGrowth%20Academy%20%E2%80%94%20I'd%20like%20to%20apply%20for%20the%20Advanced%20Digital%20Marketing%20Mentorship.%20My%20current%20role%20and%20the%20website%20I%20would%20work%20on%3A" target="_blank" rel="noopener noreferrer" data-lead-open data-lead-course="Advanced Digital Marketing Mentorship">Apply on WhatsApp <svg class="arrow"><use href="#arrow-up"></use></svg></a><a class="button ghost" href="/academy/digital-marketing-course/">See the 12-week course <svg class="arrow"><use href="#arrow-up"></use></svg></a></div><div class="in-short"><span>IN SHORT</span><p><strong>WizGrowth Academy</strong> runs this advanced digital marketing course for working professionals with 1–5 years of experience. The core course runs for 12 weeks at ₹30,000; optional mentorship continues at ₹10,000 a month.</p></div></div><div aria-hidden="true" class="hero-art"><div class="wiz-hero" data-wiz-hero="">
<span class="wiz-stage-label">LITTLE WIZ / STUDY MODE</span>
<div class="wiz-speech" data-wiz-speech="">You already know the tools.</div>
<span class="wiz-chip a">STRATEGY</span><span class="wiz-chip b">MEASURE</span><span class="wiz-chip c">LEAD</span>
<svg aria-hidden="true" class="wiz-scene-v4" viewbox="0 0 500 282">
<defs>
<lineargradient id="academy-wiz-body-fill" x1="0" x2=".85" y1="0" y2="1"><stop offset="0" stop-color="#d9ff97"></stop><stop offset=".58" stop-color="#c5f86b"></stop><stop offset="1" stop-color="#a3d84e"></stop></lineargradient>
<lineargradient id="academy-wiz-ground" x1="0" x2="1" y1="0" y2="0"><stop offset="0" stop-color="#c3b9fb" stop-opacity="0"></stop><stop offset=".5" stop-color="#c3b9fb" stop-opacity=".3"></stop><stop offset="1" stop-color="#c3b9fb" stop-opacity="0"></stop></lineargradient>
</defs>
<g fill="none" stroke="#414737" stroke-width="1"><path d="M63 75v10m-5-5h10M460 89v10m-5-5h10M116 244v10m-5-5h10"></path><ellipse cx="263" cy="247" rx="180" ry="23" stroke="url(#academy-wiz-ground)"></ellipse><ellipse cx="263" cy="247" rx="135" ry="16" stroke="url(#academy-wiz-ground)"></ellipse></g>
<ellipse class="wiz-shadow-v4" cx="249" cy="240" fill="#060805" opacity=".8" rx="66" ry="10"></ellipse>
<g class="wiz-buddy-v4">
<g class="wiz-sprout-v4"><path d="M246 78C242 49 248 39 263 25" fill="none" stroke="#c3b9fb" stroke-linecap="round" stroke-width="6"></path><path d="M249 59C216 62 211 34 209 25C235 20 252 33 249 59Z" fill="#c3b9fb" stroke="#141511" stroke-width="3"></path><path d="M250 49C247 24 266 13 288 15C286 38 273 52 250 49Z" fill="#c5f86b" stroke="#141511" stroke-width="3"></path></g>
<g stroke="#171b12" stroke-width="4"><path d="M206 209v19c-23-3-31 10-25 16c7 9 42 5 46-4l4-27" fill="#c3b9fb"></path><path d="M266 209v29c5 9 40 12 46 3c5-8-5-15-24-13v-20" fill="#c3b9fb"></path></g>
<path d="M179 149C156 153 151 171 156 185" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="12"></path>
<g class="wiz-arm-right-v4"><path d="M301 146C325 150 340 137 342 119" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="12"></path><path d="m338 120-6-7m11 5 6-9" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="6"></path></g>
<path d="M240 67C285 59 308 80 315 123C321 159 313 193 298 208C280 227 216 229 193 209C175 195 171 163 175 131C178 98 194 73 222 70Z" fill="url(#academy-wiz-body-fill)" stroke="#17220b" stroke-width="3"></path>
<path d="M190 127c0-17 6-32 19-39" fill="none" opacity=".8" stroke="#e7ffb8" stroke-linecap="round" stroke-width="5"></path>
<g class="wiz-gaze-v4"><ellipse cx="222" cy="135" fill="#202719" rx="10" ry="15"></ellipse><ellipse cx="271" cy="135" fill="#202719" rx="10" ry="15"></ellipse><ellipse cx="225" cy="130" fill="#fff" rx="3" ry="4"></ellipse><ellipse cx="274" cy="130" fill="#fff" rx="3" ry="4"></ellipse></g>
<ellipse cx="203" cy="157" fill="#c3b9fb" opacity=".75" rx="11" ry="5"></ellipse><ellipse cx="288" cy="157" fill="#c3b9fb" opacity=".75" rx="11" ry="5"></ellipse>
<path d="M231 163q15 16 29-1" fill="none" stroke="#253219" stroke-linecap="round" stroke-width="4"></path><path d="m238 202 5 7 9-15" fill="none" stroke="#5b7936" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"></path>
</g>
<g class="wiz-sparkles-v4" stroke="#c3b9fb" stroke-linecap="round" stroke-width="2"><path d="M156 83v12m-6-6h12"></path><path d="m331 48 3 5m12 4 5-1"></path><path d="m352 213 2 8m-6-5 10-2"></path></g>
</svg>
<div class="wiz-footnote"><strong>LEARN → BUILD → SHOW</strong>REAL WORK. REAL FEEDBACK.</div>
</div></div></div></div></section>
<div class="facts"><div class="fact"><span>Course</span><b>12 weeks</b></div><div class="fact"><span>Private calls</span><b>3 during course</b></div><div class="fact"><span>After course</span><b>Monthly mentorship</b></div><div class="fact"><span>Course fee</span><b>₹30,000</b></div><div class="fact"><span>Mentorship</span><b>₹10,000/month</b></div><div class="fact"><span>Group size</span><b>Max 8</b></div></div>
<section class="section"><div class="shell"><div class="section-head"><span class="eyebrow">FIT CHECK</span><span class="num">01 / 05</span></div><div class="split"><h2 class="display">Is this <span class="muted">for you?</span></h2><p class="lede">This track assumes you can already execute. The gap it targets is strategy, measurement, leadership and the confidence to own an organic-growth number.</p></div><div class="fit-grid"><div class="fit-pane"><h3>Yes, if...</h3><ul><li>You have 1–5 years in content, SEO, social or digital marketing.</li><li>You are good at execution but want to learn strategy and measurement.</li><li>You want to move towards SEO lead, content lead or organic-growth roles.</li><li>You have a live website you are allowed to work on.</li></ul></div><div class="fit-pane alt"><h3>Not for you if...</h3><ul><li>You are a complete beginner.</li><li>You want to switch specifically into performance marketing.</li><li>You cannot commit two evenings a week for 12 weeks.</li></ul></div></div></div></section>
<section class="section dark"><div class="shell"><div class="section-head"><span class="eyebrow">HOW IT WORKS</span><span class="num">02 / 05</span></div><div class="split"><h2 class="display">Same method.<br/><span class="accent">Harder track.</span></h2><div class="split-copy"><p>You join the 12-week Digital Marketing Course with AI but apply it to a real employer, client or personal website. Your week-five audit is complete, your content operation is larger, and your capstone is judged on movement in rankings and traffic, not setup.</p><p>You also get three private 30-minute calls in weeks 4, 8 and 12. After the course, the mentorship continues month to month with two group sessions and one private call each month.</p></div></div></div></section>
<section class="section" id="themes"><div class="shell"><div class="section-head"><span class="eyebrow">MENTORSHIP THEMES</span><span class="num">03 / 05</span></div><h2 class="display">Six months to build <span class="muted">range.</span></h2><div class="theme-list"><div class="theme"><span class="month">MONTH 01</span><h3>Advanced SEO</h3><p>Competitor gaps, internal linking at scale, multi-location SEO, template pages and traffic-drop recovery.</p><span class="go">↗</span></div><div class="theme"><span class="month">MONTH 02</span><h3>Content operations</h3><p>Briefs, writers and AI, editorial systems, refresh and pruning, quality control and content ROI.</p><span class="go">↗</span></div><div class="theme"><span class="month">MONTH 03</span><h3>AI search &amp; brand visibility</h3><p>Entity building, digital PR, LLM citations, AI Overviews and practical visibility tracking.</p><span class="go">↗</span></div><div class="theme"><span class="month">MONTH 04</span><h3>Measurement &amp; reporting</h3><p>Search Console at scale, GA4 explorations, organic attribution, forecasting and leadership-ready dashboards.</p><span class="go">↗</span></div><div class="theme"><span class="month">MONTH 05</span><h3>Paid + organic</h3><p>Google Ads for keyword testing, remarketing to organic visitors and when paid distribution is worth the spend.</p><span class="go">↗</span></div><div class="theme"><span class="month">MONTH 06</span><h3>Growth strategy &amp; career</h3><p>CMO-ready plans, presenting to leadership, managing writers and agencies, and negotiating the next role.</p><span class="go">↗</span></div></div></div></section>
<section class="section lilac"><div class="shell"><div class="section-head"><span class="eyebrow">WHAT YOU LEAVE WITH</span><span class="num">04 / 05</span></div><div class="split"><h2 class="display">Work that proves <span style="color:#554c73">you can lead.</span></h2><p class="lede" style="color:#554c73">A documented growth plan for a real business, ranking and traffic results, a working measurement stack, and the vocabulary to discuss strategy with a founder or CMO.</p></div><div class="number-grid"><div class="number-item"><span class="n">01</span><p>An SEO growth plan for your site.</p></div><div class="number-item"><span class="n">02</span><p>A documented content operating system.</p></div><div class="number-item"><span class="n">03</span><p>An AI-visibility audit and 90-day plan.</p></div><div class="number-item"><span class="n">04</span><p>A monthly organic report leadership can use.</p></div></div></div></section>
<section class="section" id="fees"><div class="shell"><div class="section-head"><span class="eyebrow">FEES + FAQ</span><span class="num">05 / 05</span></div><div class="price-grid"><div><h2 class="display">Start with the course.<br/><span class="muted">Continue if useful.</span></h2><div class="price">₹30,000<small>/ 12 weeks</small></div></div><div class="price-note"><p><b>The 12-week course is ₹30,000.</b> Three private calls are included.</p><p>Afterwards, mentorship is ₹10,000 a month and you can cancel any month.</p></div></div><h2 class="display faq-title">Frequently asked questions.</h2><div class="faq" id="faq"><details><summary><span>Why join the same course as freshers?</span><span>+</span></summary><p>The fundamentals are shared, but the second session each week reviews your own work at your level. Your private calls and tougher output requirements keep the professional track distinct.</p></details><details><summary><span>Can I join the mentorship without the course?</span><span>+</span></summary><p>Not in the first year. The mentorship assumes the shared method and vocabulary from the 12-week course.</p></details><details><summary><span>Will my employer pay?</span><span>+</span></summary><p>They may. WizGrowth can provide an invoice and a syllabus letter on request.</p></details></div></div></section>
<section class="cta" id="enquire"><div class="cta-code">08</div><div class="shell"><div class="cta-grid"><div><div class="eyebrow">MENTORSHIP CYCLE</div><h2>Eight seats.<br/>Bring real work.</h2></div><div class="cta-copy"><p>Message WizGrowth with your current role and the website you would work on.</p><a class="button dark" href="https://wa.me/917907551261?text=Hi%20WizGrowth%20Academy%20%E2%80%94%20I'd%20like%20to%20apply%20for%20the%20Advanced%20Digital%20Marketing%20Mentorship.%20My%20current%20role%20and%20the%20website%20I%20would%20work%20on%3A" target="_blank" rel="noopener noreferrer" data-lead-open data-lead-course="Advanced Digital Marketing Mentorship">Apply on WhatsApp <svg class="arrow"><use href="#arrow-up"></use></svg></a></div></div></div></section></main>`,
};
