// Generated from design/academy/business-owners.html by design/academy/generate.mjs.
// The markup ships verbatim so the live page stays identical to the approved
// design; regenerate this file rather than editing it by hand.
import type { AcademyPage } from './types';

export const OWNERS: AcademyPage = {
  url: "/academy/digital-marketing-for-business-owners/",
  title: "Digital Marketing for Business Owners | WizGrowth Academy",
  description: "Digital marketing for business owners: learn SEO, content and AI-search visibility on your own business. Six weeks, ₹30,000, max 10.",
  schema: {"@context":"https://schema.org","@graph":[{"@type":"Course","name":"Digital Marketing for Business Owners","description":"A six-week live course for business owners covering SEO, content, AI search visibility and measurement on their own business.","courseMode":"online","timeRequired":"P6W","provider":{"@type":"Organization","name":"WizGrowth Academy","url":"https://www.wizgrowth.com/academy/"},"offers":{"@type":"Offer","price":"30000","priceCurrency":"INR","availability":"https://schema.org/InStock"}},{"@type":"FAQPage","mainEntity":[{"@type":"Question","name":"I have no time to do marketing. Is this still useful?","acceptedAnswer":{"@type":"Answer","text":"Only if you can spend about two hours a week afterwards, or have a junior who can. Otherwise consulting is the better fit."}},{"@type":"Question","name":"Do I need a website already?","acceptedAnswer":{"@type":"Answer","text":"It helps. If you do not have one, week 2 becomes building a simple site and WizGrowth will explain the additional cost before you commit."}},{"@type":"Question","name":"Is this about running ads?","acceptedAnswer":{"@type":"Answer","text":"No. Ads are a small part of the programme. The focus is being found without paying for every click."}}]}]},
  wizMessages: ["Let's make your business findable.","Know what to do — and what to delegate.","Less guessing. More clarity."],
  html: `<div class="top"><div class="shell"><header class="site-header">
<a aria-label="WizGrowth Academy home" class="brand-lockup" href="/academy/"><span class="brand-word">wizgrowth</span><span aria-hidden="true" class="brand-divider"></span><span class="brand-section">academy</span></a>
<nav aria-label="Academy navigation" class="desktop-nav"><a href="/academy/">Academy</a><a href="#curriculum">6 weeks</a><a href="#fees">Fees</a><a href="#faq">FAQ</a></nav>
<a class="header-cta" href="#enquire"><span>Book a fit call</span><span class="header-cta-icon"><svg aria-hidden="true" class="arrow"><use href="#arrow-up"></use></svg></span></a>
<button aria-expanded="false" aria-label="Open menu" class="menu-toggle" data-menu=""><svg viewbox="0 0 24 24"><path d="M3 8h18M3 16h18" fill="none" stroke-width="1.5"></path></svg></button>
</header></div></div>
<nav aria-label="Mobile academy navigation" class="mobile-nav-v4 shell" data-mobile-nav=""><a href="/academy/">Academy</a><a href="#curriculum">6 weeks</a><a href="#fees">Fees</a><a href="#faq">FAQ</a></nav>
<main><section class="hero"><div class="shell"><div class="hero-grid"><div class="hero-copy"><div class="eyebrow kicker">WIZGROWTH ACADEMY / BUSINESS OWNERS</div><h1>Digital Marketing <span class="accent">for Business Owners.</span><span class="h1-tail">Get found on Google and AI search.</span></h1><p>Six weeks, one evening a week, working on your own business. Learn to do your own SEO, content and AI-search visibility — or learn how to judge the people you pay to do it.</p><div class="hero-actions"><a class="button lime" href="https://wa.me/917907551261?text=Hi%20WizGrowth%20Academy%20%E2%80%94%20I'd%20like%20to%20book%20a%2015-minute%20fit%20call%20about%20Digital%20Marketing%20for%20Business%20Owners." target="_blank" rel="noopener noreferrer" data-lead-open data-lead-course="Digital Marketing for Business Owners">Book a 15-minute fit call <svg class="arrow"><use href="#arrow-up"></use></svg></a><a class="button ghost" href="/services/">Prefer it done for you? <svg class="arrow"><use href="#arrow-up"></use></svg></a></div><div class="in-short"><span>IN SHORT</span><p><strong>WizGrowth Academy</strong> runs this digital marketing for business owners programme for founders who want to understand SEO, content and AI search. It runs for 6 weeks, costs ₹30,000 and is capped at 10 owners.</p></div></div><div aria-hidden="true" class="hero-art"><div class="wiz-hero" data-wiz-hero="">
<span class="wiz-stage-label">LITTLE WIZ / STUDY MODE</span>
<div class="wiz-speech" data-wiz-speech="">Let's make your business findable.</div>
<span class="wiz-chip a">SEARCH</span><span class="wiz-chip b">CONTENT</span><span class="wiz-chip c">CONTROL</span>
<svg aria-hidden="true" class="wiz-scene-v4" viewbox="0 0 500 282">
<defs>
<lineargradient id="academy-wiz-body-fill" x1="0" x2=".85" y1="0" y2="1"><stop offset="0" stop-color="#d9ff97"></stop><stop offset=".58" stop-color="#c5f86b"></stop><stop offset="1" stop-color="#a3d84e"></stop></lineargradient>
<lineargradient id="academy-wiz-ground" x1="0" x2="1" y1="0" y2="0"><stop offset="0" stop-color="#c3b9fb" stop-opacity="0"></stop><stop offset=".5" stop-color="#c3b9fb" stop-opacity=".3"></stop><stop offset="1" stop-color="#c3b9fb" stop-opacity="0"></stop></lineargradient>
</defs>
<g fill="none" stroke="#414737" stroke-width="1"><path d="M63 75v10m-5-5h10M460 89v10m-5-5h10M116 244v10m-5-5h10"></path><ellipse cx="263" cy="247" rx="180" ry="23" stroke="url(#academy-wiz-ground)"></ellipse><ellipse cx="263" cy="247" rx="135" ry="16" stroke="url(#academy-wiz-ground)"></ellipse></g>
<ellipse class="wiz-shadow-v4" cx="249" cy="240" fill="#060805" opacity=".8" rx="66" ry="10"></ellipse>
<g class="wiz-buddy-v4">
<g class="wiz-sprout-v4"><path d="M246 78C242 49 248 39 263 25" fill="none" stroke="#c3b9fb" stroke-linecap="round" stroke-width="6"></path><path d="M249 59C216 62 211 34 209 25C235 20 252 33 249 59Z" fill="#c3b9fb" stroke="#141511" stroke-width="3"></path><path d="M250 49C247 24 266 13 288 15C286 38 273 52 250 49Z" fill="#c5f86b" stroke="#141511" stroke-width="3"></path></g>
<g stroke="#171b12" stroke-width="4"><path d="M206 209v19c-23-3-31 10-25 16c7 9 42 5 46-4l4-27" fill="#c3b9fb"></path><path d="M266 209v29c5 9 40 12 46 3c5-8-5-15-24-13v-20" fill="#c3b9fb"></path></g>
<path d="M179 149C156 153 151 171 156 185" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="12"></path>
<g class="wiz-arm-right-v4"><path d="M301 146C325 150 340 137 342 119" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="12"></path><path d="m338 120-6-7m11 5 6-9" fill="none" stroke="#c5f86b" stroke-linecap="round" stroke-width="6"></path></g>
<path d="M240 67C285 59 308 80 315 123C321 159 313 193 298 208C280 227 216 229 193 209C175 195 171 163 175 131C178 98 194 73 222 70Z" fill="url(#academy-wiz-body-fill)" stroke="#17220b" stroke-width="3"></path>
<path d="M190 127c0-17 6-32 19-39" fill="none" opacity=".8" stroke="#e7ffb8" stroke-linecap="round" stroke-width="5"></path>
<g class="wiz-gaze-v4"><ellipse cx="222" cy="135" fill="#202719" rx="10" ry="15"></ellipse><ellipse cx="271" cy="135" fill="#202719" rx="10" ry="15"></ellipse><ellipse cx="225" cy="130" fill="#fff" rx="3" ry="4"></ellipse><ellipse cx="274" cy="130" fill="#fff" rx="3" ry="4"></ellipse></g>
<ellipse cx="203" cy="157" fill="#c3b9fb" opacity=".75" rx="11" ry="5"></ellipse><ellipse cx="288" cy="157" fill="#c3b9fb" opacity=".75" rx="11" ry="5"></ellipse>
<path d="M231 163q15 16 29-1" fill="none" stroke="#253219" stroke-linecap="round" stroke-width="4"></path><path d="m238 202 5 7 9-15" fill="none" stroke="#5b7936" stroke-linecap="round" stroke-linejoin="round" stroke-width="3"></path>
</g>
<g class="wiz-sparkles-v4" stroke="#c3b9fb" stroke-linecap="round" stroke-width="2"><path d="M156 83v12m-6-6h12"></path><path d="m331 48 3 5m12 4 5-1"></path><path d="m352 213 2 8m-6-5 10-2"></path></g>
</svg>
<div class="wiz-footnote"><strong>LEARN → BUILD → SHOW</strong>REAL WORK. REAL FEEDBACK.</div>
</div></div></div></div></section>
<div class="facts"><div class="fact"><span>Duration</span><b>6 weeks</b></div><div class="fact"><span>Sessions</span><b>1 live session/week</b></div><div class="fact"><span>Project</span><b>Your own business</b></div><div class="fact"><span>Fee</span><b>₹30,000</b></div><div class="fact"><span>Seats</span><b>Max 10</b></div><div class="fact"><span>Consulting</span><b>Fee can be credited</b></div></div>
<section class="section"><div class="shell"><div class="section-head"><span class="eyebrow">FIT CHECK</span><span class="num">01 / 05</span></div><div class="split"><h2 class="display">Useful if you want <span class="muted">control.</span></h2><p class="lede">This is for owners who want to understand organic growth well enough to run it themselves, guide a junior, or brief an agency without guessing.</p></div><div class="fit-grid"><div class="fit-pane"><h3>Yes, if...</h3><ul><li>You run a small business, clinic, practice, D2C brand, local service or early SaaS.</li><li>You depend heavily on referrals or ads and want more search-driven demand.</li><li>You manage your own marketing, a junior or an agency.</li><li>You want to understand whether the work you pay for is actually useful.</li></ul></div><div class="fit-pane alt"><h3>Not for you if...</h3><ul><li>You want someone else to do all the work for you.</li><li>You cannot spend about two hours a week applying the course after sessions.</li></ul></div></div></div></section>
<section class="section soft"><div class="shell"><div class="section-head"><span class="eyebrow">WHAT CHANGES</span><span class="num">02 / 05</span></div><h2 class="display">Know what to do.<br/><span class="muted">Know what to question.</span></h2><div class="number-grid"><div class="number-item"><span class="n">01</span><p>Know what people search before they buy from a business like yours.</p></div><div class="number-item"><span class="n">02</span><p>Set up your website and Google Business Profile to be easier to find.</p></div><div class="number-item"><span class="n">03</span><p>Create a content routine you or a junior can run in about two hours a week.</p></div><div class="number-item"><span class="n">04</span><p>Read Search Console and tell quickly whether organic marketing is moving.</p></div><div class="number-item"><span class="n">05</span><p>Brief an agency or hire with clearer expectations, scope and cost.</p></div></div></div></section>
<section class="section" id="curriculum"><div class="shell"><div class="section-head"><span class="eyebrow">6-WEEK OUTLINE</span><span class="num">03 / 05</span></div><h2 class="display">One business.<br/><span class="muted">Six focused weeks.</span></h2><div class="theme-list"><div class="theme"><span class="month">WEEK 01</span><h3>Positioning + search</h3><p>Ideal customer, how buyers search in Google and AI tools, and what a lead is worth.</p><span class="go">↗</span></div><div class="theme"><span class="month">WEEK 02</span><h3>Audit your website</h3><p>Technical, on-page and local review, plus Search Console and GA4 without unnecessary complexity.</p><span class="go">↗</span></div><div class="theme"><span class="month">WEEK 03</span><h3>Map demand</h3><p>Keyword research with free tools and AI, then map roughly 50 useful terms to pages.</p><span class="go">↗</span></div><div class="theme"><span class="month">WEEK 04</span><h3>Build the content routine</h3><p>Topic clusters, AI-assisted writing in your voice and a practical three-month calendar.</p><span class="go">↗</span></div><div class="theme"><span class="month">WEEK 05</span><h3>AI search + off-page</h3><p>Citations, directories, reviews, digital PR and when a small Search campaign is worth testing.</p><span class="go">↗</span></div><div class="theme"><span class="month">WEEK 06</span><h3>Measure + plan</h3><p>A one-page dashboard, weekly routine and a 90-day organic growth plan you can run or hand off.</p><span class="go">↗</span></div></div></div></section>
<section class="section dark"><div class="shell"><div class="section-head"><span class="eyebrow">HOW IT RUNS</span><span class="num">04 / 05</span></div><div class="split"><h2 class="display">Small group.<br/><span class="accent">Your business on screen.</span></h2><div class="split-copy"><p>One live two-hour session a week, on an evening or weekend, with a WhatsApp group between sessions. Every week you apply the session to your own business and get feedback the next time.</p><p>Ten owners per batch means every business gets looked at.</p></div></div></div></section>
<section class="section" id="fees"><div class="shell"><div class="section-head"><span class="eyebrow">FEES + FAQ</span><span class="num">05 / 05</span></div><div class="price-grid"><div><h2 class="display">Six weeks.<br/><span class="muted">One clear fee.</span></h2><div class="price">₹30,000<small>/ 6 weeks</small></div></div><div class="price-note"><p>If you decide within three months that you would rather have WizGrowth take ownership of your organic growth, the full course fee is credited against the first month of the Founder Growth Partner consulting engagement.</p></div></div><h2 class="display faq-title">Frequently asked questions.</h2><div class="faq" id="faq"><details><summary><span>I have no time to do marketing. Is this still useful?</span><span>+</span></summary><p>Only if you can spend about two hours a week afterwards, or have a junior who can. Otherwise consulting is the better fit.</p></details><details><summary><span>Do I need a website already?</span><span>+</span></summary><p>It helps. If you do not have one, week 2 becomes building a simple site and WizGrowth will explain the additional cost before you commit.</p></details><details><summary><span>Is this about running ads?</span><span>+</span></summary><p>No. Ads are a small part of the programme. The focus is being found without paying for every click.</p></details></div></div></section>
<section class="cta" id="enquire"><div class="cta-code">10</div><div class="shell"><div class="cta-grid"><div><div class="eyebrow">MAX 10 OWNERS</div><h2>Know whether to learn it or delegate it.</h2></div><div class="cta-copy"><p>Book a 15-minute fit call and WizGrowth will tell you whether the course or consulting is the better route.</p><a class="button dark" href="https://wa.me/917907551261?text=Hi%20WizGrowth%20Academy%20%E2%80%94%20I'd%20like%20to%20book%20a%2015-minute%20fit%20call%20about%20Digital%20Marketing%20for%20Business%20Owners." target="_blank" rel="noopener noreferrer" data-lead-open data-lead-course="Digital Marketing for Business Owners">Book a fit call <svg class="arrow"><use href="#arrow-up"></use></svg></a></div></div></div></section></main>
<footer class="site-footer"><div class="shell"><div class="footer-top"><p>Independent thinking.<br/>Forward momentum.</p><div class="footer-links"><a href="/academy/">Academy</a><a href="/academy/digital-marketing-course/">12-week course</a><a href="/academy/advanced-digital-marketing-mentorship/">Mentorship</a></div></div><div class="footer-signature"><div class="signature-main"><a class="signature-word" href="/">wiz<span>growth</span></a><button class="back-top" data-top=""><svg class="arrow"><use href="#arrow-up"></use></svg></button></div></div><div class="footer-bottom"><span>Copyright © WizGrowth Inc. 2026</span><span>A LITTLE WIZ. A LOT OF POSSIBILITY.</span><span>KERALA, INDIA ↗</span></div></div></footer>`,
};
