export { FacebookIcon } from './facebook'
export { InstagramIcon } from './instagram'
export { LinkedInIcon } from './linkedin'
export { ClockIcon } from './clock-icon'
export { TickIcon } from './tick-icon'
