/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SideMenu".
 */
export type SideMenu =
  | {
      titleId?: string | null;
      title?: string | null;
      id?: string | null;
    }[]
  | null;
/**
 * The summary box above the article. Three to five points. Leave empty to hide the box.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleTldr".
 */
export type ArticleTldr =
  | {
      /**
       * Bolded opening, e.g. "What AEO is:". Optional.
       */
      label?: string | null;
      text: string;
      id?: string | null;
    }[]
  | null;
/**
 * Shown as an expandable list under the article, and used to build FAQPage structured data. Leave empty to hide the section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleFaqs".
 */
export type ArticleFaqs =
  | {
      question: string;
      answer: string;
      id?: string | null;
    }[]
  | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    demobooking: Demobooking;
    blogInner: BlogInner;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    demobooking: DemobookingSelect<false> | DemobookingSelect<true>;
    blogInner: BlogInnerSelect<false> | BlogInnerSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    contact: Contact;
    homepage: Homepage;
    services: Service;
    'blog-home': BlogHome;
    academy: Academy;
  };
  globalsSelect: {
    contact: ContactSelect<false> | ContactSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'blog-home': BlogHomeSelect<false> | BlogHomeSelect<true>;
    academy: AcademySelect<false> | AcademySelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  profilePicture?: (number | null) | Media;
  Role?: ('admin' | 'user') | null;
  designation?: string | null;
  description?: string | null;
  socialMedia?: {
    linkedIn?: string | null;
    twitter?: string | null;
    instagram?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demobooking".
 */
export interface Demobooking {
  id: number;
  Name: string;
  Email: string;
  Date: string;
  Time: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogInner".
 */
export interface BlogInner {
  id: number;
  slug: string;
  title?: string | null;
  /**
   * The short paragraph under the headline that sets up the article. Two or three sentences.
   */
  dek?: string | null;
  /**
   * Short label for the breadcrumb trail, e.g. "What is AEO?". Falls back to the title if empty.
   */
  crumb?: string | null;
  /**
   * The date shown on the article and used for sorting. Falls back to the created date if empty.
   */
  publishedDate?: string | null;
  featuredImage?: (number | null) | Media;
  category?:
    | ('general' | 'best of' | 'ai' | 'career' | 'seo-content' | 'tools' | 'local-business' | 'academy')[]
    | null;
  readingTime?: string | null;
  sideMenu?: SideMenu;
  tldr?: ArticleTldr;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  faqs?: ArticleFaqs;
  /**
   * Up to three articles shown at the end of this one.
   */
  relatedPosts?: (number | BlogInner)[] | null;
  publishedBy?: (number | null) | User;
  updatedBy?: (number | null) | User;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    canonicalUrl?: string | null;
    metaSocial?:
      | {
          platform: 'facebook' | 'twitter';
          ogTitle?: string | null;
          ogDescription?: string | null;
          ogImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'demobooking';
        value: number | Demobooking;
      } | null)
    | ({
        relationTo: 'blogInner';
        value: number | BlogInner;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  profilePicture?: T;
  Role?: T;
  designation?: T;
  description?: T;
  socialMedia?:
    | T
    | {
        linkedIn?: T;
        twitter?: T;
        instagram?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demobooking_select".
 */
export interface DemobookingSelect<T extends boolean = true> {
  Name?: T;
  Email?: T;
  Date?: T;
  Time?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogInner_select".
 */
export interface BlogInnerSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  dek?: T;
  crumb?: T;
  publishedDate?: T;
  featuredImage?: T;
  category?: T;
  readingTime?: T;
  sideMenu?: T | SideMenuSelect<T>;
  tldr?: T | ArticleTldrSelect<T>;
  content?: T;
  faqs?: T | ArticleFaqsSelect<T>;
  relatedPosts?: T;
  publishedBy?: T;
  updatedBy?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        metaRobots?: T;
        schema?: T;
        canonicalUrl?: T;
        metaSocial?:
          | T
          | {
              platform?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SideMenu_select".
 */
export interface SideMenuSelect<T extends boolean = true> {
  titleId?: T;
  title?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleTldr_select".
 */
export interface ArticleTldrSelect<T extends boolean = true> {
  label?: T;
  text?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArticleFaqs_select".
 */
export interface ArticleFaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  id?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  Title: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    canonicalUrl?: string | null;
    metaSocial?:
      | {
          platform: 'facebook' | 'twitter';
          ogTitle?: string | null;
          ogDescription?: string | null;
          ogImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  Title: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    canonicalUrl?: string | null;
    metaSocial?:
      | {
          platform: 'facebook' | 'twitter';
          ogTitle?: string | null;
          ogDescription?: string | null;
          ogImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  Title: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    canonicalUrl?: string | null;
    metaSocial?:
      | {
          platform: 'facebook' | 'twitter';
          ogTitle?: string | null;
          ogDescription?: string | null;
          ogImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-home".
 */
export interface BlogHome {
  id: number;
  title: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    canonicalUrl?: string | null;
    metaSocial?:
      | {
          platform: 'facebook' | 'twitter';
          ogTitle?: string | null;
          ogDescription?: string | null;
          ogImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academy".
 */
export interface Academy {
  id: number;
  Title: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    keywords?: string | null;
    metaRobots?: string | null;
    schema?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    canonicalUrl?: string | null;
    metaSocial?:
      | {
          platform: 'facebook' | 'twitter';
          ogTitle?: string | null;
          ogDescription?: string | null;
          ogImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  Title?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        metaRobots?: T;
        schema?: T;
        canonicalUrl?: T;
        metaSocial?:
          | T
          | {
              platform?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  Title?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        metaRobots?: T;
        schema?: T;
        canonicalUrl?: T;
        metaSocial?:
          | T
          | {
              platform?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  Title?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        metaRobots?: T;
        schema?: T;
        canonicalUrl?: T;
        metaSocial?:
          | T
          | {
              platform?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-home_select".
 */
export interface BlogHomeSelect<T extends boolean = true> {
  title?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        metaRobots?: T;
        schema?: T;
        canonicalUrl?: T;
        metaSocial?:
          | T
          | {
              platform?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "academy_select".
 */
export interface AcademySelect<T extends boolean = true> {
  Title?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        keywords?: T;
        metaRobots?: T;
        schema?: T;
        canonicalUrl?: T;
        metaSocial?:
          | T
          | {
              platform?: T;
              ogTitle?: T;
              ogDescription?: T;
              ogImage?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatCardBlock".
 */
export interface StatCardBlock {
  /**
   * The large number, e.g. "₹3.2L" or "68%".
   */
  figure: string;
  /**
   * One or two sentences explaining the figure.
   */
  body: string;
  /**
   * Where the figure comes from. Shown in small caps beneath the body.
   */
  source?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statCard';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PullQuoteBlock".
 */
export interface PullQuoteBlock {
  quote: string;
  /**
   * Who said it. Leave empty for an unattributed pull quote.
   */
  attribution?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pullQuote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InlineCtaBlock".
 */
export interface InlineCtaBlock {
  /**
   * The line above the buttons, e.g. "Want this run for you?"
   */
  label: string;
  whatsappLabel?: string | null;
  secondaryLabel?: string | null;
  secondaryHref?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'inlineCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}